# [[headers]]
#   for = "/*"
#   [headers.values]
#     Content-Security-Policy = "default-src 'self';"

[[redirects]]
  from = "https://ruchdane.netlify.app/*"
  to = "https://ruchdane.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/ingest/static/*"
  to = "https://eu-assets.i.posthog.com/static/:splat"
  host = "eu-assets.i.posthog.com"
  status = 200
  force = true

[[redirects]]
  from = "/ingest/*"
  to = "https://eu.i.posthog.com/:splat"
  host = "us.i.posthog.com"
  status = 200
  force = true
  
